baseURL = "https://lifeibiren.github.io/"
languageCode = "zh-cn"
title = "lifeibiren's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  #author = "lifeibiren"
  description = "ä¸€åªèœç‹—"
  github = "lifeibiren"
#  facebook = "MeiK2333"
#  twitter = "MeiK2333"
#  linkedin = "MeiK2333"
#  instagram = "MeiK2333"
#  tumblr = "MeiK2333"
  email = "lifeibiren@gmail.com"
  url = "https://www.github.com/lifeibiren"
  keywords = "C++,C,GNU,blog"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
#  enableGitalk = true
  enableSearch = true

#  [params.gitalk]
#    clientID = "Your client ID" # Your client ID
#    clientSecret = "Your client secret" # Your client secret
#    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
#    owner = "ventusoon" # æ‚¨çš„GitHub ID
#    admin = "ventusoon" # æ‚¨çš„GitHub ID
#    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
#    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
#    perPage = 15 # Pagination size, with maximum 100.
#    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
#    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
#    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
#    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†

  [[params.links]]
    title = "Link"
    href = "https://github.com/lifeibiren"

lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "G-9HJP9GWSNT"